VSCODE-1050: PAT auth for hosted BitBucket(like for hosted Jira)
atlassian/atlascode pull request #28
Opened 2024-12-12 09:02 UTC by bkaindl

Like the API of Jira and Bitbucket, the API of Bitbucket supports Bearer Auth using PAT instead of Basic Auth:
https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

A number of other customers have expressed a need for this feature, not just us (Cloud Software Group): We disallow the use of HTTP Basic Auth for security reasons for the Confluence, Jira and Bitbucket APIs of our self-hosted services. Instead, we require the use of Bearer Auth using a PAT by the users.

A background information for this is that, that your security policy requires 2FA or alternatively tokens, password authentication without a 2nd factor as implemented in HTTP Basic Authentication is prohibited by company security policy, and therefore HTTP Basic Authentication is prohibited.

Also, by security policy, passwords have to be changed frequently, so even without that prohibition, password authentication would be very cumbersome as frequent changes result in frequent breakdown of the Atlascode login in VS Code.

Right now, the Atlascloud plugin supports authenticating to Jira using PAT because of a requirement by a customer, but the same has not been extended to Bitbucket, it only supports using username/password (Basic Authentication).

curl -v --oauth2-bearer $PAT https://<self-hosted bitbucket server>/rest/api/1.0/users/userslug?avatarSize=48

Bearer Authorization is already available in atlascode, but not yet enabled for Bitbucket, it just was requested for Jira and not for Bitbucket:
https://bitbucket.org/atlassianlabs/atlascode/issues/237/allow-saml-sso-as-authentication-method

All that remains for Atlascode is to allow Bearer Authorization for Bitbucket as well.

This is what this PR does. It adds the same option to alternatively use PAT auth for self-hosted Bitbucket like the Jira client of Atlascode already implements.

2024-12-12 17:07 UTC, sdzh-atlassian commented
Hi @bkaindl!

Thank you for resubmitting the PR - and once again, sorry for the trouble you experienced with CLA 🙏 

The change itself looks good to me - let me get a second pair of eyes on it (per policy 😉) and we'll see if we can roll it into our new nightly pre-releases.

For @atlassian/axon -  CI didn't run here:
 * To be proper, let's make sure the build doesn't break
 * TODO: set up build pipelines for PRs coming from forks?

2024-12-13 00:22 UTC, bwieger-atlassian-com commented on src/atlclients/clientManager.ts
> +        Logger.info(auth);
Logging Auth is probably not the right thing to do. 

Instead, we could log what type of auth we are seeing.

2024-12-13 00:23 UTC, bwieger-atlassian-com commented on src/atlclients/clientManager.ts
> +        }
The `if, else if, else` structure is missing an else statement. 

The else statement should throw something like "Auth type not recognized"

2024-12-13 00:23 UTC, bwieger-atlassian-com commented on src/atlclients/clientManager.ts
> +    private createHTTPClient(site: DetailedSiteInfo, info: AuthInfo): HTTPClient {
Thank you for refactoring!

2024-12-13 00:36 UTC, bwieger-atlassian-com requested changes
Some small changes requested

2024-12-17 04:43 UTC, bwieger-atlassian-com commented
Addressing comment in https://github.com/atlassian/atlascode/pull/41

2024-12-17 05:33 UTC, bwieger-atlassian-com commented
Addressing comments in https://github.com/atlassian/atlascode/pull/43

Thanks again @bkaindl for raising these PRs!

2024-12-17 05:33 UTC, closed without merging