[AXON-37] Implement headless E2E testing
atlassian/atlascode pull request #33
Opened 2024-12-14 04:44 UTC by sdzh-atlassian

### What is this?

A much needed break from having to stare at the VSCode UI - at least for the duration of our end-to-end tests running 😉

In all seriousness, this is an implementation of dockerized local E2E test execution. This change features 3 new commands, the docker equivalent of previously implemented ones:

```
# Build the docker image for E2E testing.
# This only needs to be done once
npm run e2e:docker:build

# Run full cycle of test setup, including rebuilding the extension
# One would typically want to do this once, and then use the last command
npm run e2e:docker

# Skip most of the test setup, and run re-compiled tests
# MUCH faster, use this to iterate over tests themselves
npm run e2e:docker:rerun
```

The way this works is by building a (relatively) small docker image with `xvfb`, `vscode` and their deps - and mounting the whole working dir in there. The tests are then run using the virtual buffer provided by `xvfb-run`. Any failed tests will produce screenshots in the local folder `e2e/.resources/screenshots`. How it looks (there are no scary VSCode popups in the process 😉):

| When tests fail | When tests succeed |
|-|-|
|![image](https://github.com/user-attachments/assets/97a2184b-db70-4c1a-a753-a6827f5cff47) | ![image](https://github.com/user-attachments/assets/60aa6566-fe43-4b62-b96f-b3df09e18d0b) |

### How was this tested

* All the new commands work
* I've built the `vsix` to make sure none of the extra stuff ends up there
* No changes to the code of the extension itself here - so didn't do any tests against that

2024-12-14 04:52 UTC, sdzh-atlassian commented on e2e/Dockerfile
> +ENTRYPOINT ["/usr/bin/entrypoint.sh"]
It took me. SO. LONG. to figure out that the issue I was having only had to do with improperly set up entrypoint 🙀 

This little built-in entrypoint script is the most elegant solution I could come up with to allow the flexibility of `docker run my-cool-app --with=fancy-options` without completely borking the whole process by using `xvfb-run` directly 😦

2024-12-16 17:27 UTC, bwieger-atlassian-com requested changes

2024-12-16 17:58 UTC, sdzh-atlassian commented on package.json
> +        "e2e:docker": "e2e/scripts/in-docker npm run e2e",
Addressed the command naming in the [follow-up PR](https://github.com/atlassian/atlascode/pull/36)

2024-12-16 18:05 UTC, sdzh-atlassian commented on e2e/tests/dummy.test.ts
> +        expect('Atlassian').to.be.oneOf(titles);
On this specific line btw - I kind of screwed up here lol. It's supposed to be
```
expect(titles).to.include('Atlassian');
```

2024-12-16 18:49 UTC, bwieger-atlassian-com approved these changes

2024-12-16 19:17 UTC, sdzh-atlassian commented
Force pushed to rebase to the previous branch in the chain, no changes, merging once the build is done
![image](https://github.com/user-attachments/assets/602cd72e-d7ab-48a4-a4ef-dbd1788e8776)

2024-12-16 19:20 UTC, merged